import _ from 'lodash'
import { Nullish } from './types'
import useLocaleStore from '../store/locale.store'
export const currencyFormats = {
  USD: '$',
  GBP: '£',
  CHF: 'Fr.',
  DKK: 'kr',
  NOK: 'kr',
  SEK: 'kr',
  TRL: '',
  CAD: 'C$',
  PLZ: 'zł',
  KES: 'KSh',
  PKR: 'Rs.',
  INR: 'Rs.',
  LBP: 'ل.ل',
  VES: 'Bs.S',
  SYP: 'SYP',
  COP: '$',
  XAF: 'BEAC',
  GIP: '£',
  ALL: 'L',
  ZWL: 'Z$',
  UYU: '$',
  MYR: 'RM',
  IRR: 'ریال',
  LKR: 'ரூ',
  ISK: 'kr',
  SOS: 'So.',
  PHP: '₱',
  CUP: '$MN',
  ETB: 'Br',
  LYD: 'LD',
  EGP: 'ج.م',
  JPY: '¥',
  THB: '฿',
  SAR: 'ر.س',
  CRC: '₡',
  GTQ: 'kn',
  SDD: '',
  TND: 'د.ت',
  NGN: '₦',
  ZAR: 'R',
  DJF: 'Fdj',
  MAD: 'د.م.',
  JOD: 'د.ا',
  IQD: 'ع.د',
  PYG: '₲',
  KWD: 'د.ك',
  HKD: 'HK$',
  XPF: '₣',
  DZD: 'دج',
  EUR: '€',
  MMK: 'K',
  AUD: 'A$',
  GHC: '',
  NZD: 'NZ$',
  AFN: 'Af',
  DOP: 'RD$',
  SVC: '₡',
  HNL: 'L',
  KRW: '₩',
  NIO: 'C$',
  YER: '﷼',
  IDR: 'Rp',
  SGD: 'S$',
  TZS: 'TSh',
  UGX: 'Ush',
  ZMK: 'ZK',
  GNF: 'FG',
  ANG: 'NAƒ',
  BSD: 'B$',
  BHD: '.د.ب',
  XCD: 'EC$',
  BMD: 'BD$',
  BND: 'B$',
  BIF: 'Fbu',
  KHR: '៛',
  JMD: '$',
  TWD: 'NT$',
  CNY: '¥',
  VND: '"    ₫"',
  FKP: '£',
  FJD: 'FJ$',
  GYD: 'GY$',
  HTG: 'G',
  BZD: 'BZ$',
  HUF: 'Ft',
  LAK: '₭',
  LRD: 'L$',
  MOP: 'MOP$',
  MWK: 'MK',
  MVR: 'Rf',
  MNT: '₮',
  NPR: '₨',
  PAB: 'B',
  RWF: '₣',
  WST: 'WS$',
  SLL: 'Le',
  TTD: 'TT$',
  TOP: 'T$',
  MUR: '₨',
  BWP: 'P',
  LSL: 'L',
  SZL: 'L',
  BDT: '৳',
  BTN: 'Nu.',
  CVE: 'Esc',
  KPW: '₩',
  OMR: 'ر.ع.',
  SCR: 'SR',
  AED: 'د.إ',
  XDR: 'SDR',
  QAR: 'ر.ق',
  PGK: 'K',
  STD: 'Db',
  GMD: 'D',
  BBD: 'BBD',
  MRO: 'UM',
  PEN: 'S/.',
  ILS: '₪',
  KYD: '$',
  SBD: 'SI$',
  SHP: '£',
  VUV: 'v',
  XOF: 'BCEAO',
  KMF: 'KMF',
  AWG: 'ƒ',
  YUM: '',
  ARS: '$',
  EEK: '',
  LVL: '',
  LTL: '',
  MXN: 'Mex$',
  CZK: 'Kč',
  KGS: 'KGS',
  TMM: '',
  HRK: 'kn',
  GEL: 'ლ',
  KZT: '〒',
  UZS: 'UZS',
  BRL: 'R$',
  MDL: 'L',
  MKD: 'ден',
  CSK: '',
  CLP: '$',
  BGL: '',
  SUR: '$',
  BOB: 'Bs.',
  ECS: '',
  AOA: 'Kz',
  YDD: '',
  MGF: '',
  ROL: '',
  MZM: '',
  DDM: '',
  SRG: '',
  MLF: '',
  GWP: '',
  GQE: '',
  ZRN: '',
  BYB: '',
  TJR: '',
  ADP: '',
  CSD: '',
  ZWN: '',
  TMT: 'm',
  YUD: '',
  BRC: '',
  BEL: '',
  UCK: '',
  PTE: '',
  PLN: 'zł',
  BAM: 'KM',
  UAH: '₴',
  ERN: 'Nfk',
  RUB: '₽',
  AMD: 'Դ',
  AON: '',
  BOV: 'BOV',
  CLF: 'UF',
  ECV: '',
  MXV: 'MXV',
  NAD: 'N$',
  TPE: '',
  CDF: 'F',
  BGN: 'лв',
  BYR: 'Br',
  TJS: 'SM',
  SRD: '$',
  TRY: '₤',
  MGA: 'Ar',
  RON: 'L',
  AZN: 'ман',
  MZN: 'MTn ',
  RSD: 'din.',
  SDG: '£',
  GHS: '₵',
  VEF: 'Bs.F',
}

const getSimboloValuta = (currency: Nullish<string>) => {
  if (!currency) return ''
  return currencyFormats[currency as keyof typeof currencyFormats] || currency
}

export const formatNumber = (value: Nullish<string | number>, options?: Intl.NumberFormatOptions) => {
  const { lang } = useLocaleStore.getState()
  if ((typeof value === 'number' || typeof value === 'string') && _.isFinite(Number(value))) {
    return Intl.NumberFormat(lang || 'it', options).format(Number(value))
  }
  return ''
}

export const formatCurrency = (
  value: Nullish<string | number>,
  currency?: Nullish<string>,
  options?: Intl.NumberFormatOptions
) => {
  const valuta = getSimboloValuta(currency || 'EUR')

  const config = {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
    ...options,
  } as Intl.NumberFormatOptions

  const importo = formatNumber(value, config)
  return importo ? `${importo} ${valuta}` : ''
}

export const formatPercentage = (value: Nullish<string | number>, options?: Intl.NumberFormatOptions) => {
  const config = {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
    ...options,
  } as Intl.NumberFormatOptions
  const formattedNumber = formatNumber(value, config)
  return formattedNumber ? `${formattedNumber} %` : ''
}
