import type { Metadata } from 'next'
import { PageParamsProps } from '@/lib/types/page.type'
import { PropsWithChildren } from 'react'
import Providers from '@/lib/providers'
import { Geist, Geist_Mono } from 'next/font/google'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = PageParamsProps & PropsWithChildren

export default async function RootLayout({ children, params }: RootLayoutProps) {
  const { lang } = await params
  return (
    <html lang={lang}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers params={params}>{children}</Providers>
      </body>
    </html>
  )
}
